service: discover-module

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage}
  region: us-east-1
  memorySize: 2048


plugins:
  - serverless-prune-plugin

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
